### ISSUE TITLE
Cycle mutliple monitors doesn't work - Kali linux 5.7.0-kali1-amd64 - VMware Workstation 15 Pro 15.5.6 build-16341506

### ISSUE THREAD

**Issue by lh20eau** [vmware/open-vm-tools#461]
**Cycle multiple monitors doesn't work:** 

_Have two clones with :_ 

**11.0.5.17716 (build-15389592)** 
**11.1.0.19887 (build-16036546)** 

_Both work._

After upgrade to : 

`vmware-toolbox-cmd -v`
`11.1.5.22735 (build-16724464)`

**Log lines from vmware.log :** 

2020-08-30T16:11:21.576+02:00| svga| I005: SVGA Driver Error: svgaPresentCmd.c:1235 BindGBScreenTarget
2020-08-30T16:11:21.576+02:00| svga| I005: SVGA Driver Error: svgaFifo.c:775 BindGBScreenTarget
2020-08-30T16:11:21.576+02:00| svga| I005: SVGA Driver Error: svgaFifo.c:2656 Unknown_

**Reinstall twice** 
**Still doesn't work.**

**Trying to build open-vm-tools-11.1.0-16036546  to rollback:**

autoreconf -1
./configure --without-pam --without-xml2

**When _make_ receive got following error :** 

`utilBacktrace.c: In function ‘Util_BacktraceWithFunc’:
utilBacktrace.c:441:4: error: array subscript -4 is outside array bounds of ‘int[1]’ [-Werror=array-bounds]
  441 |    UtilBacktraceFromPointerWithFunc(&x[-2], outFunc, outFuncData);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
utilBacktrace.c:398:28: note: while referencing ‘bugNr’
  398 | Util_BacktraceWithFunc(int bugNr,                // IN:
      |                        ~~~~^~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:507: utilBacktrace.lo] Error 1
make[2]: Leaving directory '/home/kali/Downloads/open-vm-tools-11.1.0-16036546/lib/user'
make[1]: *** [Makefile:500: all-recursive] Error 1
make[1]: Leaving directory '/home/kali/Downloads/open-vm-tools-11.1.0-16036546/lib'
make: *** [Makefile:544: all-recursive] Error 1`

**Comment by johnwvmw** [comment]
You are submitting 2 issues at once.   

The Util_BacktraceWithFunc() compilation problem with newer versions of gcc has been addressed in #429.  

Keeping this issue open for the SVGA error in the 11.1.5 open-vm-tools on Kali linux.

**Comment by lh20eau** [comment]
@johnwvmw,sorry for the duplication of these issue #429,i make a bad research and  don't found anything.

**Comment by stanguturi** [comment]
@lh20eau I have logged an internal bug for investigating the issue. Will update this issue if I get any update from the team. Thanks.

**Comment by anilnambiar** [comment]
@lh20eau We had multi monitor broken in Linux Kernel 5.7 release. Can you either try the latest 5.7 patch release or 5.8 release and let us know if cycling multiple monitor is still broken.

**Comment by Comodore125** [comment]
cycling three monitors does not work. two monitors (both different resolution) works amazingly well.
